spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user?autoReconnect=true&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: anywhere

  redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      pool:
        min-idle: 2
        max-idle: 500
        max-active: 500


mybatis:
  type-aliases-package: com.hehe.security.model
  mapper-locations: classpath*:mapper/*Mapper.xml

email:
  host: smtp.163.com
  username: m15854026443@163.com
  password: xxxxxxx

server:
  port: 8060

